### ISSUE TITLE
Crashes when field name is too long

### ISSUE THREAD

**Issue by lovre-nc** [axiomhq/axiom-js#64]
Hi, I'm using the @axiomhq/pino package and when a specific log occurred, the following error was thrown. Unfortunately I don't have access to what was being logged as I haven't been able to reproduce the specific condition again.

Now my question is, should it be the library's responsibility to check if the field name is too long?
If not, do you have a suggestion on what the best way is to handle this or at least how to catch the error?

Right now, the application silently crashes with neither the original error nor this new error getting sent to axiom.

```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: invalid field name: exceeds the max number of bytes (200)
    at FetchClient.<anonymous> (/app/node_modules/.pnpm/@axiomhq+js@0.1.3/node_modules/@axiomhq/js/src/fetchClient.ts:43:29)
    at step (/app/node_modules/.pnpm/@axiomhq+js@0.1.3/node_modules/@axiomhq/js/dist/cjs/fetchClient.js:59:23)
    at Object.next (/app/node_modules/.pnpm/@axiomhq+js@0.1.3/node_modules/@axiomhq/js/dist/cjs/fetchClient.js:40:53)
    at fulfilled (/app/node_modules/.pnpm/@axiomhq+js@0.1.3/node_modules/@axiomhq/js/dist/cjs/fetchClient.js:31:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on ThreadStream instance at:
    at Immediate.<anonymous> (/app/node_modules/.pnpm/thread-stream@2.3.0/node_modules/thread-stream/index.js:360:12)
    at process.processImmediate (node:internal/timers:476:21)
```

**Comment by ghardin1314** [comment]
Also getting a crash from passing too much data to the log. This is really unacceptable from a consumer standpoint

```
2023-09-20T19:41:33.118552+00:00 app[web.1]: node:events:492
2023-09-20T19:41:33.118598+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2023-09-20T19:41:33.118598+00:00 app[web.1]:       ^
2023-09-20T19:41:33.118598+00:00 app[web.1]: 
2023-09-20T19:41:33.118599+00:00 app[web.1]: Error: adding 'req.headers.x-hasura-allowed-roles' to dataset fields would exceed the column limit of 257
2023-09-20T19:41:33.118601+00:00 app[web.1]:     at FetchClient.<anonymous> (/srv/node_modules/@axiomhq/js/dist/cjs/fetchClient.js:127:62)
2023-09-20T19:41:33.118602+00:00 app[web.1]:     at step (/srv/node_modules/@axiomhq/js/dist/cjs/fetchClient.js:59:23)
2023-09-20T19:41:33.118602+00:00 app[web.1]:     at Object.next (/srv/node_modules/@axiomhq/js/dist/cjs/fetchClient.js:40:53)
2023-09-20T19:41:33.118603+00:00 app[web.1]:     at fulfilled (/srv/node_modules/@axiomhq/js/dist/cjs/fetchClient.js:31:58)
2023-09-20T19:41:33.118603+00:00 app[web.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-20T19:41:33.118605+00:00 app[web.1]: Emitted 'error' event on ThreadStream instance at:
2023-09-20T19:41:33.118605+00:00 app[web.1]:     at Immediate.<anonymous> (/srv/node_modules/thread-stream/index.js:363:12)
2023-09-20T19:41:33.118605+00:00 app[web.1]:     at process.processImmediate (node:internal/timers:476:21)
2023-09-20T19:41:33.118606+00:00 app[web.1]:     at process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-09-20T19:41:33.118606+00:00 app[web.1]: 
2023-09-20T19:41:33.118606+00:00 app[web.1]: Node.js v18.17.1
```

**Comment by lukasmalkmus** [comment]
@lovre-nc Hi, thanks for reporting this. Unfortunately I'm not one of the maintainers so forgive me that I cannot make a decision on this right now.

> _[]_ should it be the library's responsibility to check if the field name is too long?

If you by `library` mean `@axiomhq/js` itself my guess is, **no**. Even if client-side validation is performed, an error is still returned in case validation doesn't pass, no?

> If not, do you have a suggestion on what the best way is to handle this or at least how to catch the error?

> Right now, the application silently crashes with neither the original error nor this new error getting sent to axiom.

Unfortunately I don't have a solution for that, right now. But I definitely see the problem: `@axiomhq/pino` uses the `@axiomhq/js` provided client under the hood. When the client throws an error `@axiomhq/pino` doesn't handle that. So we definitely need to implement a feature that lets `@axiomhq/pino` detect and act differently on errors (log to console, perform user defined action, etc.).

@lovre-nc Does that sound about right?

Just having the client do validation and throw an error won't solve the problem of pino not being able to act differently on specific errors.

I definitely raise this internally and come back to you ASAP. The `@axiomhq/pino` package should definitely handle 400s like the ones you observe differently and not crash your app (as you as a user have no control over dealing with pino errors).

--

@ghardin1314 The error you observed is unrelated. You hit the field limit that is part of your free plan. Field restrictions are documented here: https://axiom.co/docs/reference/field-restrictions.

**Comment by lovre-nc** [comment]
@lukasmalkmus Thank you for looking into it. You hit the nail on the head 🙂

I had a quick look on how other transports handle this scenario:

pino-loki simply does a `console.error` with the resulting error and provides a `silenceErrors` option disable that behavior. [source](https://github.com/Julien-R44/pino-loki/blob/dev/src/log_pusher/index.ts#L34) 

pino-datadog-transport provides an `onError` option and calls that function if provided. [source](https://github.com/theogravity/pino-datadog-transport/blob/master/src/process-logs.ts#L142)
However, this option requires a bit of work for the user because functions can't easily be supplied in the pino options. [(see here)](https://github.com/theogravity/pino-datadog-transport#implementing-the-onerror--ondebug-callback) When doing something similar in the recent past, I encountered difficulties because of our module resolution and ESM setup.

I think catching the error and preventing a crash should be the highest priority, more advanced options and/or a console log are appreciated but up to you.

**Comment by lukasmalkmus** [comment]
@lovre-nc Thanks, appreciate the detailed insights on the other pino packages. This will help use short-circuit decision making, thanks a lot! :)

**Comment by schehata** [comment]
@lovre-nc we now provide `onError` method that defaults to console.log the error on axiom-js. But for pino, still need to figure out a way for this to work on workers. passing `onError` to pino options fails because the workers can't pass functions through `postMessage`.

**Comment by lovre-nc** [comment]
@schehata if it doesn't crash anymore, I consider this issue solved.
